import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import icon from "./images/shopping-bag.png";
import Link from "next/link";
import { StoreProvider } from "./redux/StoreProvider";
import CartIcon from "./conponents/CartIcon";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}>
          <header className=" bg-slate-800 h-[9%] flex justify-between items-center p-3">
            <Link href="/">
              <Image src={icon} width={80} height={80} alt="Picture of the author" />
            </Link>

            <CartIcon />
          </header>
          {children}
          <footer className=" bg-slate-800 h-[7%] text-xl flex items-center justify-center">
            <h2>Footer</h2>
          </footer>
        </body>
      </html>
    </StoreProvider>
  );
}
